version: "3.9"
services:
  db:
    image: postgres:latest
    volumes:
     - saltykov_test_case:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "avito_test_case"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "8001:5432"
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      TC_PG_HOST: "db"
      TC_PG_PORT: "5432"
      TC_OG_USER: "postgres"
      TC_PG_PASSWORD: "postgres"
    depends_on:
      - db
    ports:
      - "8080:8080"


volumes:
  saltykov_test_case: