version: "3.9"
services:
  db:
    build:
      dockerfile: DockerfilePostgres
    environment:
      POSTGRES_DB: "avito_test_case"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "8001:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      TC_PG_HOST: "db"
      TC_PG_PORT: "5432"
      TC_OG_USER: "postgres"
      TC_PG_PASSWORD: "postgres"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"