app:
  name : 'AVITO_TEST_CASE_SALTYKOV'
  AssignmentCleaningInterval : '3600'

http:
  port : '8080'

log:
  level : 'INFO'

postgres:
  host : 'localhost'
  port : '8001'
  user : 'database'
  password : 'postgres'
  db : 'avito_test_case'
  poolMaxOpen : '10'
  poolMaxIdle : '10'
  poolMaxLifeTime : '600'
  reconnectAttempts : '3'
  LogLevel : 'WARN'
